namePrefix: dev-
commonLabels:
  variant: development



# apply a patch to replace the Host of the Route
#- patch: |-
#    - op: replace
#      path: /spec/host
#      value: art-test.apps-crc.testing
#  target:
#    kind: Route
# this patch needs to be done, because kustomize does not change 
# the route target service name
patches:
- patch: |-
    - op: replace
      path: /spec/to/name
      value: dev-simple
  target:
    kind: Route
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- digest: sha256:77caaa227349475062eccbede76c4debc5cb252976e5d9f6aa52eb8ddce6c761
  name: quay.io/wpernath/simple-quarkus:latest
  newName: quay.io/wpernath/quarkus-simple-wow
